{% set name = "numthreads" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/numthreads-{{ version }}.tar.gz
  sha256: 60863221aa2bfefe8220f4d636899c00d2e54d7c482ca67db54fa29cd0246a7b

build:
  entry_points:
    - numthreads = numthreads:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - numthreads
  commands:
    - pip check
    - numthreads --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Ultra tiny and simple tool to set the number of threads for OpenBLAS, MKL, OMP, NumExpr, and Accelerate.
  description: |
    `numthreads` is a really tiny and simple Python package designed to set the number of threads for various computing libraries including OpenBLAS, Intel's Math Kernel Library (MKL), OpenMP, NumExpr, and Accelerate.
    The number of threads can be set via the command line or in Python code.
    The performance of many numerical algorithms varies significantly based on the number of threads employed.
    While increasing the number of threads can often accelerate these algorithms, it's not always the case.
    In some instances, using more threads may actually impede computational efficiency.
    Therefore, it's important to be able to easily set the number of threads used by these libraries.
  license: MIT
  license_file: LICENSE
  home: https://github.com/basnijholt/numthreads/
  doc_url: http://numthreads.readthedocs.org
  dev_url: https://github.com/basnijholt/numthreads/

extra:
  recipe-maintainers:
    - basnijholt
